# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        user:
#            id: Lockate\APIBundle\Security\UserProvider
#        in_memory:
#            memory: ~
#        in_memory:
#            memory:
#                users:
#                    schmier:
#                        password: destruction
#                        roles: 'ROLE_USER'

        fos_userbundle:
            id: fos_user.user_provider.username
            # it could be email
            # ex:  id: fos_user.user_provider.username_email

    encoders:
        Lockate\APIBundle\Entity\User: bcrypt
        FOS\UserBundle\Model\UserInterface: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

            guard:
                authenticators:
                    - Lockate\APIBundle\Security\JwtTokenAuthenticator
                    #- Lockate\APIBundle\Security\TokenAuthenticator

            # if you want, disable storing the user in the session
            # stateless: true

            # maybe other things, like form_login, remember_me, etc
            # ...

            # FOSUserBundle needed to get the token
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: true
                default_target_path:            /site
            #remember_me:
            #    secret: '%secret%'
            #logout: ~

    access_control:
          - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN