lockate_site_homepage:
    path:     /
    defaults: { _controller: LockateAPIBundle:Default:index }

lockate_site_initial:
    path: /site
    defaults: { _controller: LockateAPIBundle:Site:inside }

lockate_api_sensors:
    path:   /api/v1/sensors
    defaults: { _controller: LockateAPIBundle:Api:sensors }
    methods:  [POST]

lockate_api_sensors_payload:
    path:   /api/v1/senseddata
    defaults: { _controller: LockateAPIBundle:Api:sensedData }
    methods:  [POST]

lockate_api_tokens:
    path:   /api/v1/tokens
    defaults: { _controller: LockateAPIBundle:Token:newToken }
    methods:  [POST]

lockate_api_gateway:
    path:   /api/v1/gateway/{gateway_id}/{limit}
    defaults: { _controller: LockateAPIBundle:Api:gatewayId, limit: null }
    requirements:
        gateway_id: '\d+'
    methods: [GET]

lockate_api_gateway_sensors:
    path:   /api/v1/gatewaysensors/{gateway_id}/{limit}
    defaults: { _controller: LockateAPIBundle:Api:gatewaySensors, limit: null }
    requirements:
        gateway_id: '\d+'
    methods: [GET]

lockate_api_sensor_info:
    path:   /api/v1/sensorinfo/{sensor_id}/{limit}
    defaults: { _controller: LockateAPIBundle:Api:sensorDetails, limit: null }
    requirements:
        gateway_id: '\d+'
    methods: [GET]
